# Production namespaces for octo-apm-demo on OKE.

apiVersion: v1
kind: Namespace
metadata:
  name: octo-drone-shop
  labels:
    app.kubernetes.io/part-of: octo-apm-demo
    app.kubernetes.io/component: shop
    octo.oracle.com/tier: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-crm
  labels:
    app.kubernetes.io/part-of: octo-apm-demo
    app.kubernetes.io/component: crm
    octo.oracle.com/tier: production
