# Production namespaces for octo-apm-demo on OKE.

apiVersion: v1
kind: Namespace
metadata:
  name: ${K8S_NAMESPACE_SHOP}
  labels:
    app.kubernetes.io/part-of: octo-apm-demo
    app.kubernetes.io/component: shop
    octo.oracle.com/tier: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: ${K8S_NAMESPACE_CRM}
  labels:
    app.kubernetes.io/part-of: octo-apm-demo
    app.kubernetes.io/component: crm
    octo.oracle.com/tier: production
