-- genai_kb — RAG knowledge base for AI Studio (Oracle 19c compatible).
--
-- The emdemo ATP is Oracle 19c (no native VECTOR type), so embeddings are stored
-- as JSON text in a CLOB column and cosine similarity is computed app-side in
-- services/genai-studio/app/db/vector_search.py. On a 23ai DB you may instead use
-- `embedding VECTOR(1024, FLOAT32)` + a VECTOR index and swap the ranking SQL.
--
-- ADDITIVE / SAFE: creates one new table + a read grant. Never alters the shop
-- tables (orders / products / order_items). Idempotent (ORA-00955 swallowed).
-- Run once as the schema owner that owns `products` (so seeding can read it):
--   sqlplus <writer>/<pw>@<dsn> @genai_kb.sql
-- Then seed: python -m scripts.seed_genai_kb  (writeable SEED_DB_* user).
--
-- The read-only AI Studio user is parameterised; override with:
--   sqlplus ... @genai_kb.sql   (defaults to STUDIO_RO)

DEFINE studio_ro_user = STUDIO_RO

SET SERVEROUTPUT ON

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE genai_kb (
      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source      VARCHAR2(40)  NOT NULL,   -- 'product' | 'doc'
      ref_id      VARCHAR2(120),            -- product id or doc slug
      title       VARCHAR2(400),
      chunk       CLOB          NOT NULL,    -- the text that was embedded
      embedding   CLOB,                      -- JSON array of floats (app-side cosine)
      updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('genai_kb created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('genai_kb already exists - skipping create');
    ELSE
      RAISE;
    END IF;
END;
/

-- Read-only access for the AI Studio agent user (studio_ro).
GRANT SELECT ON genai_kb TO &studio_ro_user;

PROMPT genai_kb migration complete. Seed with: python -m scripts.seed_genai_kb
