-- genai_kb — knowledge base for the AI Studio RAG agent (Oracle 23ai native VECTOR)
--
-- ADDITIVE / SAFE: creates one new table + grant + index. Never alters the shop
-- tables (orders / products / order_items). Run ONCE as the schema owner that
-- owns the shop tables (so `products` is visible for seeding).
--
-- Idempotent: re-running is a no-op (ORA-00955 "name already used" is swallowed).
--
-- Prereqs: Oracle 23ai (VECTOR type). Verify with:
--   SELECT value FROM nls_database_parameters WHERE parameter='NLS_RDBMS_VERSION';  -- >= 23
--
-- The embedding dimension MUST match STUDIO_EMBED_DIM / the embed model
-- (cohere.embed-*-v3.0 = 1024).  Change VECTOR(1024, ...) if you change models.
--
-- The read-only studio user is parameterised via a SQL*Plus DEFINE; override on
-- the command line with:  sqlplus ... @genai_kb_23ai.sql   (defaults to STUDIO_RO)

DEFINE studio_ro_user = STUDIO_RO

SET SERVEROUTPUT ON

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE genai_kb (
      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source      VARCHAR2(40)  NOT NULL,   -- 'product' | 'doc'
      ref_id      VARCHAR2(120),            -- product id or doc slug
      title       VARCHAR2(400),
      chunk       CLOB          NOT NULL,    -- the text that was embedded
      embedding   VECTOR(1024, FLOAT32),    -- Cohere v3 = 1024 dims
      updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('genai_kb created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('genai_kb already exists - skipping create');
    ELSE
      RAISE;
    END IF;
END;
/

-- Read-only access for the AI Studio agent user.
GRANT SELECT ON genai_kb TO &studio_ro_user;

-- Best-effort HNSW vector index. A small KB works fine with a full scan, so any
-- index failure (option not enabled, already exists) is non-fatal.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE VECTOR INDEX genai_kb_vec_idx ON genai_kb (embedding)
      ORGANIZATION INMEMORY NEIGHBOR GRAPH
      DISTANCE COSINE
      WITH TARGET ACCURACY 95
  ]';
  DBMS_OUTPUT.PUT_LINE('genai_kb_vec_idx created');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('genai_kb_vec_idx skipped: ' || SQLERRM);
END;
/

PROMPT genai_kb migration complete. Seed with: python -m scripts.seed_genai_kb
