"""Seed the genai_kb knowledge base with product + doc embeddings.

ADMIN-run (writes genai_kb). Reads the catalog read-only, embeds each product
row and each curated drone-domain doc with OCI GenAI, and stores the vectors in
``genai_kb`` for the AI Studio RAG agent.

Connection: uses a *writeable* DB user via SEED_DB_* (never studio_ro). Falls
back to STUDIO_DB_* only if those already point at a writeable user. Embeddings
use the studio's OCI GenAI settings (OCI_GENAI_EMBED_MODEL_ID / endpoint /
compartment / auth).

Idempotent: performs a full rebuild (DELETE then INSERT) so re-running refreshes
the KB. Safe: only ever writes to ``genai_kb``; reads the catalog SELECT-only.

Usage (in the studio pod or anywhere with the ADMIN wallet):
    SEED_DB_USER=ADMIN SEED_DB_PASSWORD=... SEED_DB_DSN=... \
    STUDIO_ORACLE_WALLET_DIR=/wallet python -m scripts.seed_genai_kb [--skip-ddl]
"""

from __future__ import annotations

import argparse
import json
import logging
import os
from pathlib import Path
from typing import Any

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger("seed_genai_kb")

_KNOWLEDGE = Path(__file__).resolve().parent.parent / "db" / "knowledge" / "drone-knowledge.json"

_DDL = """
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE genai_kb (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR2(40) NOT NULL, ref_id VARCHAR2(120), title VARCHAR2(400),
    chunk CLOB NOT NULL, embedding VECTOR(%(dim)s, FLOAT32),
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
"""


def _seed_connect_kwargs() -> dict[str, Any]:
    user = os.getenv("SEED_DB_USER") or os.getenv("STUDIO_DB_USER")
    password = os.getenv("SEED_DB_PASSWORD") or os.getenv("STUDIO_DB_PASSWORD")
    dsn = os.getenv("SEED_DB_DSN") or os.getenv("STUDIO_DB_DSN")
    if not (user and password and dsn):
        raise SystemExit("SEED_DB_USER / SEED_DB_PASSWORD / SEED_DB_DSN required (writeable user)")
    if user.lower() == "studio_ro":
        raise SystemExit("refusing to seed as read-only user studio_ro; set SEED_DB_USER to a writeable user")
    kwargs: dict[str, Any] = {"user": user, "password": password, "dsn": dsn}
    wallet = os.getenv("STUDIO_ORACLE_WALLET_DIR")
    if wallet:
        kwargs["config_dir"] = wallet
        kwargs["wallet_location"] = wallet
    wpw = os.getenv("STUDIO_ORACLE_WALLET_PASSWORD")
    if wpw:
        kwargs["wallet_password"] = wpw
    return kwargs


def _lob(value: Any) -> str:
    return value.read() if hasattr(value, "read") else ("" if value is None else str(value))


def _product_chunk(row: dict[str, Any]) -> str:
    parts = [f"{row.get('name')} ({row.get('category')})"]
    if row.get("sku"):
        parts.append(f"SKU {row['sku']}")
    desc = _lob(row.get("description"))
    if desc:
        parts.append(desc)
    specs = _lob(row.get("specs"))
    if specs:
        parts.append(f"Specs: {specs}")
    parts.append(
        f"Price: {row.get('price')}. In stock: {row.get('stock')}. "
        f"Rating: {row.get('rating')} ({row.get('review_count')} reviews)."
    )
    return " | ".join(str(p) for p in parts if p)


def _load_records(conn) -> list[dict[str, Any]]:
    """Build (source, ref_id, title, chunk) records from catalog + curated docs."""
    records: list[dict[str, Any]] = []
    with conn.cursor() as cur:
        cur.execute(
            "SELECT id, name, category, price, stock, description, sku, specs, "
            "rating, review_count FROM products WHERE is_active = 1"
        )
        cols = [c[0].lower() for c in cur.description]
        for raw in cur.fetchall():
            row = dict(zip(cols, raw))
            records.append({
                "source": "product",
                "ref_id": str(row.get("id")),
                "title": str(row.get("name"))[:400],
                "chunk": _product_chunk(row),
            })
    if _KNOWLEDGE.exists():
        docs = json.loads(_KNOWLEDGE.read_text()).get("docs", [])
        for doc in docs:
            records.append({
                "source": "doc",
                "ref_id": doc["slug"],
                "title": doc["title"][:400],
                "chunk": doc["text"],
            })
    return records


def _embedder():
    from app.config import get_settings
    from langchain_oci.embeddings import OCIGenAIEmbeddings

    s = get_settings()
    if not s.genai_configured:
        raise SystemExit("OCI GenAI not configured (OCI_GENAI_MODEL_ID / COMPARTMENT_ID)")
    return OCIGenAIEmbeddings(
        model_id=s.genai_embed_model_id,
        service_endpoint=s.genai_endpoint,
        compartment_id=s.genai_compartment_id,
        auth_type=s.oci_auth_type,
    ), s.embed_dim


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed genai_kb embeddings")
    parser.add_argument("--skip-ddl", action="store_true", help="assume genai_kb already exists")
    parser.add_argument("--batch", type=int, default=64, help="embedding batch size")
    args = parser.parse_args()

    import oracledb

    embedder, dim = _embedder()
    with oracledb.connect(**_seed_connect_kwargs()) as conn:
        if not args.skip_ddl:
            with conn.cursor() as cur:
                cur.execute(_DDL % {"dim": dim})
            conn.commit()
            logger.info("ensured genai_kb (dim=%s)", dim)

        records = _load_records(conn)
        logger.info("built %d records (products + docs)", len(records))
        texts = [r["chunk"] for r in records]

        vectors: list[list[float]] = []
        for i in range(0, len(texts), args.batch):
            vectors.extend(embedder.embed_documents(texts[i:i + args.batch]))
            logger.info("embedded %d/%d", min(i + args.batch, len(texts)), len(texts))

        with conn.cursor() as cur:
            cur.execute("DELETE FROM genai_kb")
            cur.executemany(
                "INSERT INTO genai_kb (source, ref_id, title, chunk, embedding) "
                "VALUES (:source, :ref_id, :title, :chunk, TO_VECTOR(:emb))",
                [
                    {**{k: rec[k] for k in ("source", "ref_id", "title", "chunk")},
                     "emb": json.dumps(vec)}
                    for rec, vec in zip(records, vectors)
                ],
            )
        conn.commit()
        logger.info("seeded %d rows into genai_kb", len(records))


if __name__ == "__main__":
    main()
