{{- if .Values.crm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: enterprise-crm-portal
  namespace: {{ .Values.crm.namespace }}
  labels:
    {{- include "octo.labels" . | nindent 4 }}
    {{- include "octo.crm.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.crm.service.type }}
  selector:
    {{- include "octo.crm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.crm.service.port }}
      targetPort: http
{{- end }}
